# Generated by Django 5.1.15 on 2026-05-28 02:19

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubwayStation',
            fields=[
                ('id', models.CharField(help_text='역 ID (RDS subway_station.id, varchar(20)).', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="역명 (예: '충무로')", max_length=100)),
                ('line', models.CharField(help_text="노선 (예: '3호선')", max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='역 위치 (WGS84). GiST 인덱스.', srid=4326)),
                ('adong', models.ForeignKey(blank=True, db_column='adong_code', help_text='행정동. regions snapshot 교체 시 NULL 허용.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subway_stations', to='regions.adong')),
                ('ldong', models.ForeignKey(blank=True, db_column='ldong_code', help_text='법정동. regions snapshot 교체 시 NULL 허용.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subway_stations', to='regions.ldong')),
            ],
            options={
                'verbose_name': '지하철역',
                'verbose_name_plural': '지하철역',
                'db_table': 'subway_station',
                'ordering': ['line', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubwayCongestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_type', models.CharField(help_text='평일/토요일/일요일/휴일 (CHECK ck_subway_congestion_day_type 4종)', max_length=20)),
                ('direction', models.CharField(help_text='상선/하선/내선/외선 (CHECK ck_subway_congestion_direction 4종)', max_length=20)),
                ('express_yn', models.CharField(help_text='일반/급행 (CHECK ck_subway_congestion_express_yn 2종)', max_length=10)),
                ('time', models.TimeField(help_text='시간대')),
                ('congestion', models.DecimalField(decimal_places=4, help_text='혼잡도 % (서울교통공사 기준 100=정원, 0~200+ 가능)', max_digits=12)),
                ('station', models.ForeignKey(db_column='station_id', on_delete=django.db.models.deletion.CASCADE, related_name='congestions', to='subway.subwaystation')),
            ],
            options={
                'verbose_name': '지하철 혼잡도',
                'verbose_name_plural': '지하철 혼잡도',
                'db_table': 'subway_congestion',
            },
        ),
        migrations.CreateModel(
            name='NearestSubwayAdong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.SmallIntegerField(help_text='1~3')),
                ('station_name', models.CharField(help_text='지하철역 이름 (비정규화)', max_length=100)),
                ('distance_m', models.FloatField(help_text='측지선 m (>= 0)')),
                ('adong', models.ForeignKey(db_column='adong_code', on_delete=django.db.models.deletion.CASCADE, related_name='nearest_subways', to='regions.adong')),
            ],
            options={
                'verbose_name': '가까운 지하철역 (행정동, 사전계산)',
                'verbose_name_plural': '가까운 지하철역 (행정동, 사전계산)',
                'db_table': 'nearest_subway_adong',
                'ordering': ['adong', 'rank'],
                'indexes': [models.Index(fields=['station_name'], name='ix_nearest_subway_adong_name')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rank__gte', 1), ('rank__lte', 3)), name='ck_nearest_subway_adong_rank'), models.CheckConstraint(condition=models.Q(('distance_m__gte', 0)), name='ck_nearest_subway_adong_distance')],
                'unique_together': {('adong', 'rank')},
            },
        ),
        migrations.CreateModel(
            name='NearestSubwayLdong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.SmallIntegerField(help_text='1~3')),
                ('station_name', models.CharField(help_text='지하철역 이름 (비정규화)', max_length=100)),
                ('distance_m', models.FloatField(help_text='측지선 m (>= 0)')),
                ('ldong', models.ForeignKey(db_column='ldong_code', on_delete=django.db.models.deletion.CASCADE, related_name='nearest_subways', to='regions.ldong')),
            ],
            options={
                'verbose_name': '가까운 지하철역 (법정동, 사전계산)',
                'verbose_name_plural': '가까운 지하철역 (법정동, 사전계산)',
                'db_table': 'nearest_subway_ldong',
                'ordering': ['ldong', 'rank'],
                'indexes': [models.Index(fields=['station_name'], name='ix_nearest_subway_ldong_name')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rank__gte', 1), ('rank__lte', 3)), name='ck_nearest_subway_ldong_rank'), models.CheckConstraint(condition=models.Q(('distance_m__gte', 0)), name='ck_nearest_subway_ldong_distance')],
                'unique_together': {('ldong', 'rank')},
            },
        ),
        migrations.AddIndex(
            model_name='subwaystation',
            index=django.contrib.postgres.indexes.GistIndex(fields=['location'], name='subway_location_gist_idx'),
        ),
        migrations.AddIndex(
            model_name='subwaystation',
            index=models.Index(fields=['adong'], name='subway_stat_adong_c_77e870_idx'),
        ),
        migrations.AddIndex(
            model_name='subwaystation',
            index=models.Index(fields=['ldong'], name='subway_stat_ldong_c_9e7181_idx'),
        ),
        migrations.AddIndex(
            model_name='subwaystation',
            index=models.Index(fields=['name'], name='subway_stat_name_1fcc5b_idx'),
        ),
        migrations.AddIndex(
            model_name='subwaycongestion',
            index=models.Index(fields=['station', 'day_type'], name='subway_cong_station_43fb82_idx'),
        ),
        migrations.AddIndex(
            model_name='subwaycongestion',
            index=models.Index(fields=['day_type', 'time'], name='subway_cong_day_typ_f2d5b8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subwaycongestion',
            unique_together={('station', 'day_type', 'direction', 'express_yn', 'time')},
        ),
    ]
