# Generated by Django 5.1.15 on 2026-05-27 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0007_rename_adjacent_ad_adong_c_c2bcba_idx_adjacent_ad_adong1__7a7873_idx_and_more'),
        ('subway', '0007_region_fk_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subwaystation',
            name='adong',
            field=models.ForeignKey(blank=True, db_column='adong_code', help_text='행정동. regions snapshot 교체 시 NULL 허용.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subway_stations', to='regions.adong'),
        ),
        migrations.AlterField(
            model_name='subwaystation',
            name='ldong',
            field=models.ForeignKey(blank=True, db_column='ldong_code', help_text='법정동. regions snapshot 교체 시 NULL 허용.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subway_stations', to='regions.ldong'),
        ),
    ]
