# Generated by Codex on 2026-06-03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts_favorites", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateRegion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("region_level", models.CharField(choices=[("adong", "행정동"), ("ldong", "법정동")], max_length=8)),
                ("slug", models.CharField(max_length=160)),
                ("code", models.CharField(blank=True, max_length=40)),
                ("gu", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=80)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                ("score", models.FloatField(blank=True, null=True)),
                ("score_rent", models.FloatField(blank=True, null=True)),
                ("score_transit", models.FloatField(blank=True, null=True)),
                ("score_amenity", models.FloatField(blank=True, null=True)),
                ("score_safety", models.FloatField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("conditions", "추천"), ("map", "지도"), ("detail", "동네 정보")],
                        default="map",
                        max_length=16,
                    ),
                ),
                ("added_at_ms", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_regions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "담은 동네",
                "verbose_name_plural": "담은 동네",
                "db_table": "user_candidate_region",
                "ordering": ["-added_at_ms", "-updated_at"],
                "indexes": [models.Index(fields=["user", "-added_at_ms"], name="user_cand_user_id_4efc_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "region_level", "slug"), name="uniq_user_candidate_region")
                ],
            },
        ),
    ]
