# Generated by Django 5.1.15 on 2026-05-28 02:19

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('convenience', '편의점'), ('mart', '마트'), ('restaurant', '음식점'), ('cafe', '카페'), ('hospital', '병원'), ('dental', '치과'), ('pharmacy', '약국'), ('pet', '반려동물'), ('laundry', '세탁소'), ('beauty', '미용'), ('oliveyoung', '올리브영'), ('gym', '체육시설'), ('nightlife', '주점'), ('book_stationery', '서점/문구'), ('pc_room', 'PC방'), ('etc', '기타'), ('park', '공원'), ('library', '도서관'), ('university', '대학교'), ('subway_station', '지하철역'), ('bus_stop', '버스정류장')], help_text='시설 카테고리 (17종, ck_amenity_category)', max_length=30)),
                ('name', models.CharField(help_text='시설 명칭. park는 원천 name+" "+park.category 결합 (예: "장미공원 어린이공원"). 그 외는 원천 name 그대로.', max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='시설 위치 (WGS84). GiST 인덱스.', srid=4326)),
                ('source_table', models.CharField(choices=[('store', 'store'), ('park', 'park'), ('library', 'library'), ('univ', 'univ'), ('subway_station', 'subway_station'), ('bus_stop', 'bus_stop')], help_text='원천 테이블명 (6종, ck_amenity_source_table)', max_length=30)),
                ('source_id', models.CharField(help_text='원천 PK 값 그대로. store.id / park.id / library.id / univ.id / subway_station.id / bus_stop.id', max_length=64)),
            ],
            options={
                'verbose_name': '생활시설',
                'verbose_name_plural': '생활시설',
                'db_table': 'amenity',
                'indexes': [models.Index(fields=['category'], name='amenity_categor_4570df_idx'), django.contrib.postgres.indexes.GistIndex(fields=['location'], name='amenity_location_gist_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_table', 'source_id'), name='uq_amenity_source')],
            },
        ),
        migrations.CreateModel(
            name='AmenityAdong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adong', models.ForeignKey(db_column='adong_code', on_delete=django.db.models.deletion.CASCADE, related_name='amenity_links', to='regions.adong')),
                ('amenity', models.ForeignKey(db_column='amenity_id', on_delete=django.db.models.deletion.CASCADE, related_name='adong_links', to='amenities.amenity')),
            ],
            options={
                'verbose_name': '생활시설 ↔ 행정동',
                'verbose_name_plural': '생활시설 ↔ 행정동',
                'db_table': 'amenity_adong',
                'indexes': [models.Index(fields=['amenity'], name='amenity_ado_amenity_5d63e4_idx'), models.Index(fields=['adong'], name='amenity_ado_adong_c_7226c7_idx')],
                'unique_together': {('amenity', 'adong')},
            },
        ),
        migrations.CreateModel(
            name='AmenityLdong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(db_column='amenity_id', on_delete=django.db.models.deletion.CASCADE, related_name='ldong_links', to='amenities.amenity')),
                ('ldong', models.ForeignKey(db_column='ldong_code', on_delete=django.db.models.deletion.CASCADE, related_name='amenity_links', to='regions.ldong')),
            ],
            options={
                'verbose_name': '생활시설 ↔ 법정동',
                'verbose_name_plural': '생활시설 ↔ 법정동',
                'db_table': 'amenity_ldong',
                'indexes': [models.Index(fields=['amenity'], name='amenity_ldo_amenity_6c118b_idx'), models.Index(fields=['ldong'], name='amenity_ldo_ldong_c_9dfdd4_idx')],
                'unique_together': {('amenity', 'ldong')},
            },
        ),
    ]
