# Generated by Django 5.1.15 on 2026-05-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0008_region_links_cascade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='category',
            field=models.CharField(choices=[('convenience', '편의점'), ('mart', '마트'), ('restaurant', '음식점'), ('cafe', '카페'), ('hospital', '병원'), ('dental', '치과'), ('pharmacy', '약국'), ('pet', '반려동물'), ('laundry', '세탁소'), ('beauty', '미용'), ('oliveyoung', '올리브영'), ('gym', '체육시설'), ('nightlife', '주점'), ('book_stationery', '서점/문구'), ('pc_room', 'PC방'), ('etc', '기타'), ('park', '공원'), ('library', '도서관'), ('university', '대학교'), ('subway_station', '지하철역'), ('bus_stop', '버스정류장')], help_text='시설 카테고리 (17종, ck_amenity_category)', max_length=30),
        ),
    ]
