# Generated by Django 5.1.15 on 2026-05-28 02:19

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.CharField(help_text='공원 ID (RDS park.id, varchar(50)). SHP UPIS_SHP_ZON216의 ID에서 끝 4자리 추출 후 P prefix. 예: 생활서비스시설_공원_0033 → P0033', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='공원 이름 (NOT NULL)', max_length=200)),
                ('category', models.CharField(help_text='공원 분류 (NOT NULL). 근린공원/어린이공원/도시자연공원/마을마당/광장 등 SHP LABEL의 첫 분류 토큰', max_length=50)),
                ('area_m2', models.DecimalField(decimal_places=4, help_text='면적 (m^2, NOT NULL)', max_digits=20)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(help_text='공원 경계 (WGS84, NOT NULL)', srid=4326)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='중심점 (WGS84, NOT NULL)', srid=4326)),
            ],
            options={
                'verbose_name': '공원',
                'verbose_name_plural': '공원',
                'db_table': 'park',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category'], name='park_categor_4c7933_idx'), django.contrib.postgres.indexes.GistIndex(fields=['boundary'], name='park_boundary_gist_idx'), django.contrib.postgres.indexes.GistIndex(fields=['location'], name='park_location_gist_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParkAdong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adong', models.ForeignKey(db_column='adong_code', on_delete=django.db.models.deletion.CASCADE, related_name='park_dongs', to='regions.adong')),
                ('park', models.ForeignKey(db_column='park_id', on_delete=django.db.models.deletion.CASCADE, related_name='park_dongs', to='parks.park')),
            ],
            options={
                'verbose_name': '공원-행정동 매핑',
                'verbose_name_plural': '공원-행정동 매핑',
                'db_table': 'park_adong',
                'indexes': [models.Index(fields=['park'], name='park_adong_park_id_3c3b3d_idx'), models.Index(fields=['adong'], name='park_adong_adong_c_30d82b_idx')],
                'unique_together': {('park', 'adong')},
            },
        ),
        migrations.CreateModel(
            name='ParkLdong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldong', models.ForeignKey(db_column='ldong_code', on_delete=django.db.models.deletion.CASCADE, related_name='park_ldongs', to='regions.ldong')),
                ('park', models.ForeignKey(db_column='park_id', on_delete=django.db.models.deletion.CASCADE, related_name='park_ldongs', to='parks.park')),
            ],
            options={
                'verbose_name': '공원-법정동 매핑',
                'verbose_name_plural': '공원-법정동 매핑',
                'db_table': 'park_ldong',
                'indexes': [models.Index(fields=['park'], name='park_ldong_park_id_8414f7_idx'), models.Index(fields=['ldong'], name='park_ldong_ldong_c_385dc6_idx')],
                'unique_together': {('park', 'ldong')},
            },
        ),
    ]
