# Generated by Django 5.1.15 on 2026-05-28 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdongPopulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='기준일')),
                ('total_population', models.IntegerField(help_text='총 인구')),
                ('household_count', models.IntegerField(help_text='세대 수')),
                ('male_population', models.IntegerField(help_text='남자 인구')),
                ('female_population', models.IntegerField(help_text='여자 인구')),
                ('adong', models.ForeignKey(db_column='adong_code', on_delete=django.db.models.deletion.CASCADE, related_name='populations', to='regions.adong')),
            ],
            options={
                'verbose_name': '행정동 인구',
                'verbose_name_plural': '행정동 인구',
                'db_table': 'adong_population',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['adong', '-date'], name='adong_popul_adong_c_d66610_idx'), models.Index(fields=['date'], name='adong_popul_date_2c797b_idx')],
                'unique_together': {('adong', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LdongPopulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='기준일')),
                ('total_population', models.IntegerField(help_text='총 인구')),
                ('household_count', models.IntegerField(help_text='세대 수')),
                ('male_population', models.IntegerField(help_text='남자 인구')),
                ('female_population', models.IntegerField(help_text='여자 인구')),
                ('ldong', models.ForeignKey(db_column='ldong_code', on_delete=django.db.models.deletion.CASCADE, related_name='populations', to='regions.ldong')),
            ],
            options={
                'verbose_name': '법정동 인구',
                'verbose_name_plural': '법정동 인구',
                'db_table': 'ldong_population',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['ldong', '-date'], name='ldong_popul_ldong_c_9123bf_idx'), models.Index(fields=['date'], name='ldong_popul_date_4249ae_idx')],
                'unique_together': {('ldong', 'date')},
            },
        ),
    ]
