# Generated by Django 5.1.15 on 2026-05-28 02:19

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KsciCategory',
            fields=[
                ('ksci_code', models.CharField(help_text='KSCI 코드 (RDS PK)', max_length=20, primary_key=True, serialize=False)),
                ('subcategory_name', models.CharField(help_text='소분류명', max_length=100)),
                ('class_name', models.CharField(help_text='세분류명', max_length=100)),
                ('subclass_name', models.CharField(help_text='세세분류명', max_length=100)),
                ('middle_category_name', models.CharField(help_text='중분류명', max_length=100)),
                ('main_category_name', models.CharField(help_text='대분류명', max_length=100)),
            ],
            options={
                'verbose_name': '한국표준산업분류',
                'verbose_name_plural': '한국표준산업분류',
                'db_table': 'ksci_category',
                'ordering': ['ksci_code'],
            },
        ),
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('subcategory_code', models.CharField(help_text='소분류 코드 (RDS PK)', max_length=20, primary_key=True, serialize=False)),
                ('subcategory_name', models.CharField(help_text='소분류명', max_length=100)),
                ('middle_category_code', models.CharField(help_text='중분류 코드', max_length=20)),
                ('middle_category_name', models.CharField(help_text='중분류명', max_length=100)),
                ('main_category_code', models.CharField(help_text='대분류 코드', max_length=20)),
                ('main_category_name', models.CharField(help_text='대분류명', max_length=100)),
            ],
            options={
                'verbose_name': '소상공인 카테고리',
                'verbose_name_plural': '소상공인 카테고리',
                'db_table': 'business_category',
                'ordering': ['subcategory_code'],
                'indexes': [models.Index(fields=['middle_category_code'], name='business_ca_middle__106a60_idx'), models.Index(fields=['main_category_code'], name='business_ca_main_ca_6484ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.CharField(help_text='상가 ID (RDS store.id, varchar(50))', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='상호명 (NOT NULL)', max_length=100)),
                ('branch_name', models.CharField(blank=True, help_text='지점명 (schema.dbml NULL 허용)', max_length=100, null=True)),
                ('address', models.CharField(help_text='주소 (NOT NULL)', max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='상가 위치 (WGS84, schema.dbml NOT NULL).', srid=4326)),
                ('adong', models.ForeignKey(blank=True, db_column='adong_code', help_text='행정동. regions snapshot 교체 시 NULL 허용.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='regions.adong')),
                ('category', models.ForeignKey(db_column='category_code', help_text='소상공인 소분류 (schema.dbml NOT NULL).', on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='store.businesscategory')),
                ('ksci', models.ForeignKey(blank=True, db_column='ksci_code', help_text='한국표준산업분류 (API 응답 결측 시 NULL 허용).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='store.kscicategory')),
                ('ldong', models.ForeignKey(blank=True, db_column='ldong_code', help_text='법정동. regions snapshot 교체 시 NULL 허용.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stores', to='regions.ldong')),
            ],
            options={
                'verbose_name': '상가',
                'verbose_name_plural': '상가',
                'db_table': 'store',
                'indexes': [models.Index(fields=['adong'], name='store_adong_c_b8a0a4_idx'), models.Index(fields=['ldong'], name='store_ldong_c_a49541_idx'), models.Index(fields=['category'], name='store_categor_a63bc0_idx'), models.Index(fields=['ksci'], name='store_ksci_co_e67d73_idx'), django.contrib.postgres.indexes.GistIndex(fields=['location'], name='store_location_gist_idx')],
            },
        ),
    ]
