# Generated by Django 5.1.15 on 2026-05-27 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_agent', '0001_user_ai_api_key'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='useraiapikey',
            new_name='user_ai_api_user_id_df8124_idx',
            old_name='user_ai_api_user_id_9a4e8d_idx',
        ),
    ]
