# Generated by Django 5.1.15 on 2026-05-28 02:19

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentDeal',
            fields=[
                ('id', models.CharField(help_text='8자리 ldong + 1~2자 housing 코드 + YYMMDD + NNN, dash 없음. 예: 11010100A260514001', max_length=60, primary_key=True, serialize=False)),
                ('housing_type', models.CharField(choices=[('아파트', '아파트'), ('연립', '연립'), ('다세대', '다세대'), ('연립다세대', '연립다세대'), ('다가구', '다가구'), ('단독', '단독'), ('오피스텔', '오피스텔')], help_text='아파트, 연립다세대, 다가구, 단독, 오피스텔 (5종)', max_length=20)),
                ('jibun', models.CharField(blank=True, help_text="'법정동 + 지번' 원문 (NULL 허용)", max_length=50, null=True)),
                ('house_name', models.CharField(blank=True, help_text='건물명 (NULL 허용)', max_length=100, null=True)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=4, help_text='전용면적 ㎡. NULL 허용 (응답 결측 시 그대로 유지).', max_digits=12, null=True)),
                ('floor', models.SmallIntegerField(blank=True, help_text='층 (지하 음수)', null=True)),
                ('construction_year', models.SmallIntegerField(blank=True, help_text='건축 연도. 응답 그대로 보존 (이상치 포함).', null=True)),
                ('deposit', models.BigIntegerField(help_text='보증금 (만원, NOT NULL)')),
                ('monthly_rent', models.IntegerField(help_text='월세 (만원, NOT NULL). 0이면 전세.')),
                ('contract_date', models.DateField(help_text='계약일 (NOT NULL)')),
                ('contract_end_date', models.DateField(blank=True, help_text='계약 종료일', null=True)),
                ('contract_type', models.CharField(blank=True, help_text='신규, 갱신 (CHECK ck_rent_deal_contract_type, NULL 허용)', max_length=20, null=True)),
                ('renewal_request_right_used', models.BooleanField(blank=True, help_text='갱신요구권 사용 여부', null=True)),
                ('previous_deposit', models.BigIntegerField(blank=True, help_text='종전 계약 보증금 (만원)', null=True)),
                ('previous_monthly_rent', models.IntegerField(blank=True, help_text='종전 계약 월세 (만원)', null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='지번 보유 행의 외부 지오코딩 API 결과. 단독/다가구 또는 신뢰 불가 좌표는 NULL.', null=True, srid=4326)),
                ('adong', models.ForeignKey(blank=True, db_column='adong_code', help_text='행정동. 확실한 ldong 포함/동일 또는 신뢰 가능한 위치 매핑만 저장.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_deals', to='regions.adong')),
                ('ldong', models.ForeignKey(blank=True, db_column='ldong_code', help_text='법정동. regions snapshot 교체 시 NULL 허용.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_deals', to='regions.ldong')),
            ],
            options={
                'verbose_name': '전월세 실거래',
                'verbose_name_plural': '전월세 실거래',
                'db_table': 'rent_deal',
                'ordering': ['-contract_date'],
                'indexes': [models.Index(fields=['ldong', 'contract_date'], name='rent_deal_ldong_c_7caf73_idx'), models.Index(fields=['adong', 'contract_date'], name='rent_deal_adong_contract_idx'), models.Index(fields=['housing_type', 'contract_date'], name='rent_deal_housing_0163a0_idx'), models.Index(fields=['housing_type'], name='rent_deal_housing_438bed_idx'), django.contrib.postgres.indexes.GistIndex(fields=['location'], name='rentdeal_location_gist_idx')],
            },
        ),
        migrations.CreateModel(
            name='RentDealLdongAdongMap',
            fields=[
                ('ldong', models.OneToOneField(db_column='ldong_code', help_text='Legal dong. One mapping decision per ldong.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rent_deal_adong_map', serialize=False, to='regions.ldong')),
                ('adong', models.ForeignKey(blank=True, db_column='adong_code', help_text='Admin dong when this ldong maps to exactly one adong; otherwise NULL.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_deal_ldong_maps', to='regions.adong')),
            ],
            options={
                'verbose_name': 'rent deal ldong-adong map',
                'verbose_name_plural': 'rent deal ldong-adong maps',
                'db_table': 'rent_deal_ldong_adong_map',
                'indexes': [models.Index(fields=['adong'], name='rent_ld_ad_map_adong_idx')],
            },
        ),
    ]
