# Generated by Django 5.1.15 on 2026-05-27 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0007_rename_adjacent_ad_adong_c_c2bcba_idx_adjacent_ad_adong1__7a7873_idx_and_more'),
        ('rent_deal', '0008_region_fk_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentdeal',
            name='adong',
            field=models.ForeignKey(blank=True, db_column='adong_code', help_text='행정동. 확실한 ldong 포함/동일 또는 신뢰 가능한 위치 매핑만 저장.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_deals', to='regions.adong'),
        ),
        migrations.AlterField(
            model_name='rentdeal',
            name='ldong',
            field=models.ForeignKey(blank=True, db_column='ldong_code', help_text='법정동. regions snapshot 교체 시 NULL 허용.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_deals', to='regions.ldong'),
        ),
        migrations.AlterField(
            model_name='rentdealldongadongmap',
            name='adong',
            field=models.ForeignKey(blank=True, db_column='adong_code', help_text='Admin dong when this ldong maps to exactly one adong; otherwise NULL.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_deal_ldong_maps', to='regions.adong'),
        ),
        migrations.AlterField(
            model_name='rentdealldongadongmap',
            name='ldong',
            field=models.OneToOneField(db_column='ldong_code', help_text='Legal dong. One mapping decision per ldong.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rent_deal_adong_map', serialize=False, to='regions.ldong'),
        ),
    ]
