# Generated by Django 5.1.15 on 2026-05-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_deal', '0009_alter_rentdeal_adong_alter_rentdeal_ldong_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentdeal',
            name='housing_type',
            field=models.CharField(choices=[('아파트', '아파트'), ('연립', '연립'), ('다세대', '다세대'), ('연립다세대', '연립다세대'), ('다가구', '다가구'), ('단독', '단독'), ('오피스텔', '오피스텔')], help_text='아파트, 연립다세대, 다가구, 단독, 오피스텔 (5종)', max_length=20),
        ),
    ]
