# Generated by Django 5.1.15 on 2026-05-30

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("school", models.CharField(blank=True, default="", max_length=80)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("nickname", models.CharField(blank=True, default="", max_length=30)),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                ("home_location", django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ("address_geocode_status", models.CharField(blank=True, default="not_provided", max_length=20)),
                ("address_geocode_error", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "verbose_name": "사용자 프로필",
                "verbose_name_plural": "사용자 프로필",
                "db_table": "user_profile",
            },
        ),
    ]
