# Generated by Django 5.1.15 on 2026-05-28 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentAdong',
            fields=[
                ('score_rent', models.FloatField(blank=True, null=True)),
                ('score_amenity', models.FloatField()),
                ('score_transit', models.FloatField()),
                ('score_safety', models.FloatField(default=0.0)),
                ('score_total', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('rank_rent', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_amenity', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_transit', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_safety', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_total', models.PositiveIntegerField(blank=True, null=True)),
                ('adong', models.OneToOneField(db_column='adong_code', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='current_score', serialize=False, to='regions.adong')),
            ],
            options={
                'db_table': 'current_adong',
            },
        ),
        migrations.CreateModel(
            name='CurrentGu',
            fields=[
                ('score_rent', models.FloatField(blank=True, null=True)),
                ('score_amenity', models.FloatField()),
                ('score_transit', models.FloatField()),
                ('score_safety', models.FloatField(default=0.0)),
                ('score_total', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('rank_rent', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_amenity', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_transit', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_safety', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_total', models.PositiveIntegerField(blank=True, null=True)),
                ('gu', models.OneToOneField(db_column='gu_code', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='current_score', serialize=False, to='regions.gu')),
            ],
            options={
                'db_table': 'current_gu',
            },
        ),
        migrations.CreateModel(
            name='CurrentLdong',
            fields=[
                ('score_rent', models.FloatField(blank=True, null=True)),
                ('score_amenity', models.FloatField()),
                ('score_transit', models.FloatField()),
                ('score_safety', models.FloatField(default=0.0)),
                ('score_total', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('rank_rent', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_amenity', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_transit', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_safety', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_total', models.PositiveIntegerField(blank=True, null=True)),
                ('ldong', models.OneToOneField(db_column='ldong_code', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='current_score', serialize=False, to='regions.ldong')),
            ],
            options={
                'db_table': 'current_ldong',
            },
        ),
        migrations.CreateModel(
            name='CurrentSeoul',
            fields=[
                ('score_rent', models.FloatField(blank=True, null=True)),
                ('score_amenity', models.FloatField()),
                ('score_transit', models.FloatField()),
                ('score_safety', models.FloatField(default=0.0)),
                ('score_total', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('seoul', models.OneToOneField(db_column='code', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='current_score', serialize=False, to='regions.seoul')),
            ],
            options={
                'db_table': 'current_seoul',
            },
        ),
    ]
