# Generated by Django 5.1.15 on 2026-05-28 02:19

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seoul',
            fields=[
                ('code', models.CharField(help_text='서울시 코드 (RDS seoul.code)', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="이름 (예: '서울특별시')", max_length=100)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=4, help_text='면적 (m^2)', max_digits=20, null=True)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='서울시 경계 (WGS84)', null=True, srid=4326)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='중심점 (WGS84)', null=True, srid=4326)),
            ],
            options={
                'verbose_name': '서울',
                'verbose_name_plural': '서울',
                'db_table': 'seoul',
            },
        ),
        migrations.CreateModel(
            name='Gu',
            fields=[
                ('gu_code', models.CharField(help_text='자치구 코드 (RDS gu.gu_code)', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="구 이름 (예: '중구')", max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='URL용 고유 식별자. gu.name과 동일값 (예: 강남구)', max_length=80, null=True, unique=True)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=4, help_text='면적 (m^2)', max_digits=20, null=True)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='구 경계 (WGS84)', null=True, srid=4326)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='중심점 (WGS84)', null=True, srid=4326)),
            ],
            options={
                'verbose_name': '자치구',
                'verbose_name_plural': '자치구',
                'db_table': 'gu',
                'ordering': ['gu_code'],
                'indexes': [django.contrib.postgres.indexes.GistIndex(fields=['boundary'], name='gu_boundary_gist_idx')],
            },
        ),
        migrations.CreateModel(
            name='Adong',
            fields=[
                ('adong_code', models.CharField(help_text='행정동 코드 (RDS adong.adong_code)', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='행정동 이름', max_length=100)),
                ('slug', models.SlugField(help_text='URL용 고유 식별자. 패턴: <gu_name>-<name> (예: 강남구-신사동)', max_length=80, unique=True)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=4, help_text='면적 (m^2)', max_digits=20, null=True)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='행정동 경계 (WGS84)', null=True, srid=4326)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='중심점 (WGS84)', null=True, srid=4326)),
                ('gu', models.ForeignKey(db_column='gu_code', help_text='속한 자치구 (RDS adong.gu_code)', on_delete=django.db.models.deletion.PROTECT, related_name='adongs', to='regions.gu')),
            ],
            options={
                'verbose_name': '행정동',
                'verbose_name_plural': '행정동',
                'db_table': 'adong',
                'ordering': ['adong_code'],
            },
        ),
        migrations.CreateModel(
            name='GuAdjacency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gu_a', models.ForeignKey(db_column='gu1_code', on_delete=django.db.models.deletion.CASCADE, related_name='adjacency_a', to='regions.gu')),
                ('gu_b', models.ForeignKey(db_column='gu2_code', on_delete=django.db.models.deletion.CASCADE, related_name='adjacency_b', to='regions.gu')),
            ],
            options={
                'verbose_name': '자치구 인접',
                'verbose_name_plural': '자치구 인접',
                'db_table': 'adjacent_gu',
            },
        ),
        migrations.CreateModel(
            name='Ldong',
            fields=[
                ('ldong_code', models.CharField(help_text='법정동 코드 (RDS ldong.ldong_code)', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='법정동 이름', max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='URL용 고유 식별자. 패턴: <gu_name>-<name> (예: 강남구-신사동)', max_length=80, null=True, unique=True)),
                ('area_m2', models.DecimalField(blank=True, decimal_places=4, help_text='면적 (m^2)', max_digits=20, null=True)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='법정동 경계 (WGS84)', null=True, srid=4326)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='중심점 (WGS84)', null=True, srid=4326)),
                ('gu', models.ForeignKey(db_column='gu_code', help_text='속한 자치구 (RDS ldong.gu_code)', on_delete=django.db.models.deletion.PROTECT, related_name='ldongs', to='regions.gu')),
            ],
            options={
                'verbose_name': '법정동',
                'verbose_name_plural': '법정동',
                'db_table': 'ldong',
                'ordering': ['ldong_code'],
            },
        ),
        migrations.CreateModel(
            name='LdongAdjacency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldong_a', models.ForeignKey(db_column='ldong1_code', on_delete=django.db.models.deletion.CASCADE, related_name='adjacency_a', to='regions.ldong')),
                ('ldong_b', models.ForeignKey(db_column='ldong2_code', on_delete=django.db.models.deletion.CASCADE, related_name='adjacency_b', to='regions.ldong')),
            ],
            options={
                'verbose_name': '법정동 인접',
                'verbose_name_plural': '법정동 인접',
                'db_table': 'adjacent_ldong',
            },
        ),
        migrations.CreateModel(
            name='AdongAdjacency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adong_a', models.ForeignKey(db_column='adong1_code', on_delete=django.db.models.deletion.CASCADE, related_name='adjacency_a', to='regions.adong')),
                ('adong_b', models.ForeignKey(db_column='adong2_code', on_delete=django.db.models.deletion.CASCADE, related_name='adjacency_b', to='regions.adong')),
            ],
            options={
                'verbose_name': '행정동 인접',
                'verbose_name_plural': '행정동 인접',
                'db_table': 'adjacent_adong',
                'indexes': [models.Index(fields=['adong_a'], name='adjacent_ad_adong1__7a7873_idx'), models.Index(fields=['adong_b'], name='adjacent_ad_adong2__8155e5_idx')],
                'unique_together': {('adong_a', 'adong_b')},
            },
        ),
        migrations.AddIndex(
            model_name='adong',
            index=django.contrib.postgres.indexes.GistIndex(fields=['boundary'], name='adong_boundary_gist_idx'),
        ),
        migrations.AddIndex(
            model_name='guadjacency',
            index=models.Index(fields=['gu_a'], name='adjacent_gu_gu1_cod_11c194_idx'),
        ),
        migrations.AddIndex(
            model_name='guadjacency',
            index=models.Index(fields=['gu_b'], name='adjacent_gu_gu2_cod_ccdc76_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='guadjacency',
            unique_together={('gu_a', 'gu_b')},
        ),
        migrations.AddIndex(
            model_name='ldong',
            index=models.Index(fields=['gu'], name='ldong_gu_code_af3dfe_idx'),
        ),
        migrations.AddIndex(
            model_name='ldong',
            index=django.contrib.postgres.indexes.GistIndex(fields=['boundary'], name='ldong_boundary_gist_idx'),
        ),
        migrations.AddIndex(
            model_name='ldongadjacency',
            index=models.Index(fields=['ldong_a'], name='adjacent_ld_ldong1__a4b139_idx'),
        ),
        migrations.AddIndex(
            model_name='ldongadjacency',
            index=models.Index(fields=['ldong_b'], name='adjacent_ld_ldong2__08c33b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ldongadjacency',
            unique_together={('ldong_a', 'ldong_b')},
        ),
    ]
