# Generated by Django 5.1.15 on 2026-05-28 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentDealCache',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type_code', models.CharField(max_length=1)),
                ('deposit', models.IntegerField(help_text='Deposit amount in KRW 10,000 units.')),
                ('monthly_rent', models.SmallIntegerField(help_text='Monthly rent in KRW 10,000 units.')),
                ('converted_rent', models.SmallIntegerField(help_text='Rounded monthly rent plus deposit conversion, in KRW 10,000 units.')),
                ('area_m2', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('contract_ymd', models.IntegerField(help_text='Contract date as YYYYMMDD.')),
            ],
            options={
                'verbose_name': 'rent deal cache',
                'verbose_name_plural': 'rent deal caches',
                'db_table': 'rent_deal_cache',
                'managed': False,
            },
        ),
    ]
