# Generated by Django 5.1.15 on 2026-05-28 02:19

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.CharField(help_text='정류장 ID (RDS bus_stop.id, varchar(20)).', max_length=20, primary_key=True, serialize=False)),
                ('stop_number', models.CharField(blank=True, help_text='정류소번호 (서울 BIS arsId). RDS bus_stop.stop_number 1:1. schema.dbml NULL 허용 (line 245).', max_length=20, null=True)),
                ('name', models.CharField(help_text='정류장 명칭 (NOT NULL)', max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='정류장 위치 (WGS84). 매칭 불가 시 NULL 보존 (가상·차고지·미정차 등, schema.dbml line 249).', null=True, srid=4326)),
                ('adong', models.ForeignKey(blank=True, db_column='adong_code', help_text='행정동 (nullable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus_stops', to='regions.adong')),
                ('ldong', models.ForeignKey(blank=True, db_column='ldong_code', help_text='법정동 (nullable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus_stops', to='regions.ldong')),
            ],
            options={
                'verbose_name': '버스 정류장',
                'verbose_name_plural': '버스 정류장',
                'db_table': 'bus_stop',
            },
        ),
        migrations.CreateModel(
            name='BusCongestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='기준일')),
                ('time', models.TimeField(help_text='시간대 0~23')),
                ('congestion', models.DecimalField(decimal_places=4, help_text='혼잡도 (RouteCongestionLevel API 응답값. 시간대·노선 평균. 단위는 응답 그대로, 보통 0~210). NOT NULL.', max_digits=12)),
                ('bus_stop', models.ForeignKey(db_column='bus_stop_id', on_delete=django.db.models.deletion.CASCADE, related_name='congestions', to='bus.busstop')),
            ],
            options={
                'verbose_name': '버스 혼잡도',
                'verbose_name_plural': '버스 혼잡도',
                'db_table': 'bus_congestion',
            },
        ),
        migrations.AddIndex(
            model_name='busstop',
            index=models.Index(fields=['adong'], name='bus_stop_adong_c_711295_idx'),
        ),
        migrations.AddIndex(
            model_name='busstop',
            index=models.Index(fields=['ldong'], name='bus_stop_ldong_c_33a3d6_idx'),
        ),
        migrations.AddIndex(
            model_name='busstop',
            index=models.Index(fields=['stop_number'], name='bus_stop_stop_nu_874697_idx'),
        ),
        migrations.AddIndex(
            model_name='busstop',
            index=django.contrib.postgres.indexes.GistIndex(fields=['location'], name='busstop_location_gist_idx'),
        ),
        migrations.AddIndex(
            model_name='buscongestion',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['date'], name='buscongestion_date_brin_idx'),
        ),
        migrations.AddIndex(
            model_name='buscongestion',
            index=models.Index(fields=['bus_stop', '-date'], name='bus_congest_bus_sto_c2984d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='buscongestion',
            unique_together={('bus_stop', 'date', 'time')},
        ),
    ]
