# Generated by Django 5.1.15 on 2026-05-30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("provider", models.CharField(choices=[("kakao", "Kakao")], max_length=30)),
                ("provider_user_id", models.CharField(max_length=191)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("nickname", models.CharField(blank=True, default="", max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_social_account",
                "indexes": [models.Index(fields=["user", "provider"], name="user_social_user_id_58a646_idx")],
                "unique_together": {("provider", "provider_user_id")},
            },
        ),
    ]
